<a href="https://colab.research.google.com/github/Taniriya/Python_programming_labs_2_course/blob/main/lab1/lab1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np


a = np.random.randint(1, 11, size=(5, 5))
b = np.random.randint(1, 11, size=(5, 5))

print(a)
print(b)

[[ 6  7  4  1  7]
 [ 1  4  1  7  9]
 [ 3  7  5  9  6]
 [ 4 10  7  8  5]
 [ 7  6  5  3  5]]
[[1 7 3 1 2]
 [5 3 7 5 8]
 [5 8 9 1 3]
 [3 1 7 7 6]
 [4 7 9 8 2]]


In [15]:
# Поэлементное произведение матриц
print(a * b)

[[ 6 49 12  1 14]
 [ 5 12  7 35 72]
 [15 56 45  9 18]
 [12 10 49 56 30]
 [28 42 45 24 10]]


In [16]:
# Матричное произведение
print(a @ b)

[[ 92 145 173 108 100]
 [ 83  97 170 143  97]
 [114 133 220 154 143]
 [133 157 246 157 167]
 [ 91 145 174 103 105]]


In [23]:
# Определитель матрицы A
print(round(np.linalg.det(a)))

182


In [24]:
# Транспонирование матрицы B
print(b.T)

[[1 5 5 3 4]
 [7 3 8 1 7]
 [3 7 9 7 9]
 [1 5 1 7 8]
 [2 8 3 6 2]]


In [25]:
# Обратная матрица для A
try:
    print(np.linalg.inv(a))
except np.linalg.LinAlgError:
    print("Матрица должна быть квадратной")

[[-1.85714286  1.57142857 -3.28571429  1.85714286  1.85714286]
 [-2.05494505  1.97252747 -4.27472527  2.67032967  1.78571429]
 [ 4.20879121 -3.8956044   8.04395604 -4.74725275 -3.78571429]
 [-1.15384615  0.92307692 -1.76923077  1.07692308  1.        ]
 [ 1.54945055 -1.22527473  2.74725275 -1.7032967  -1.35714286]]


In [26]:
# Находим С — вектор-столбец сумм строк матрицы A
c = np.sum(a, axis=1)
print(c)

[25 22 30 34 26]


In [27]:
# Решаем уравнение A * x = C
x = np.linalg.solve(a, c)
print(x)
print("Проверка:")
print(a @ x)
# C равно a @ x

[1. 1. 1. 1. 1.]
Проверка:
[25. 22. 30. 34. 26.]
