<a href="https://colab.research.google.com/github/Taniriya/Python_programming_labs_2_course/blob/main/lab1/lab1_6_extra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import time


class Timer:
    def __enter__(self):
        self.start_time = time.time()

    def __exit__(self, type, value, traceback):
        total_time = time.time() - self.start_time
        print(f"Total time: {total_time} seconds")


# Пример использования контекстного менеджера
with Timer() as timer:
    a = np.random.randint(1, 11, size=(5, 5))
    b = np.random.randint(1, 11, size=(5, 5))
    print(a)
    print(b)
    print(a * b)
    print(a @ b)
    print(round(np.linalg.det(a)))
    print(b.T)
    try:
        print(np.linalg.inv(a))
    except np.linalg.LinAlgError:
        print("Матрица должна быть квадратной")
    c = np.sum(a, axis=1)
    print(c)
    x = np.linalg.solve(a, c)
    print(x)
    print(a @ x)

[[ 1  6  9  7  9]
 [10  3  8  8  5]
 [ 7  7  6  8  6]
 [ 1  7  6  2 10]
 [ 1  2  3 10  4]]
[[ 9 10  6  8  7]
 [ 7  2  4  1  4]
 [ 7  5  7  1  7]
 [ 4 10  1  9  1]
 [ 2  5  6  5  6]]
[[ 9 60 54 56 63]
 [70  6 32  8 20]
 [49 35 42  8 42]
 [ 4 70  6 18 10]
 [ 2 10 18 50 24]]
[[160 182 154 131 155]
 [209 251 166 188 176]
 [198 224 156 171 163]
 [128 124 138  89 139]
 [ 92 149  69 123  70]]
-9472
[[ 9  7  7  4  2]
 [10  2  5 10  5]
 [ 6  4  7  1  6]
 [ 8  1  1  9  5]
 [ 7  4  7  1  6]]
[[-0.14759291  0.10451858  0.0032728   0.07801943  0.00147804]
 [ 0.09100507 -0.19320101  0.29698057 -0.1139147  -0.12394426]
 [ 0.29159628  0.01668074 -0.01361909 -0.19562922 -0.16744088]
 [-0.00147804 -0.02470439  0.02649916 -0.04571368  0.10874155]
 [-0.22360642  0.11972128 -0.20534206  0.29845861  0.16532939]]
[32 34 34 26 20]
[1. 1. 1. 1. 1.]
[32. 34. 34. 26. 20.]
Total time: 0.004724264144897461 seconds
